
name: Native-Ruby-Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
   Native-Ruby-Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repo
      uses: actions/checkout@v2
      with:
        repository: KennaPublicSamples/toolkit
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Install dependencies
      run: bundle config set without 'test development'
    - name:  Run Toolkit
      run : ruby toolkit.rb task=help
      
